// <auto-generated />
namespace StockExchange.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApplicationUser_Stocks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplicationUser_Stocks));
        
        string IMigrationMetadata.Id
        {
            get { return "201601151641532_ApplicationUser_Stocks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
